/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf 
Author: SunnyBuns (https://sketchfab.com/SunnyBuns)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/penguin-plush-228fddb7362f42e2a349b84cbe8191b4
Title: Penguin plush
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes["Box001_02_-_Default_0"].geometry}
          material={materials["02_-_Default"]}
          position={[0, 23.004, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.54}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
