/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf 
Author: SunnyBuns (https://sketchfab.com/SunnyBuns)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/penguin-plush-228fddb7362f42e2a349b84cbe8191b4
Title: Penguin plush
*/
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";

function Penguin(props: any) {
  const meshRef = useRef<THREE.Mesh>(null!);
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const { nodes, materials }: any = useGLTF("/scene.gltf");

  const sensitivity = 1000;

  useEffect(() => {
    const handleMouseMove = (event: any) => {
      setMousePosition({
        x: event.clientY / sensitivity,
        y: event.clientX / sensitivity,
      });
    };

    window.addEventListener("mousemove", handleMouseMove);

    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
    };
  }, []);

  useFrame((state, delta) => {
    meshRef.current.rotation.x = mousePosition.x;
    meshRef.current.rotation.y = mousePosition.y - 1000;
  });

  return (
    <group {...props} dispose={null} ref={meshRef}>
      <group scale={0.02}>
        <mesh
          geometry={nodes["Box001_02_-_Default_0"].geometry}
          material={materials["02_-_Default"]}
          position={[0, -50, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.54}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");

export default Penguin;
